ElectroniceDeviceWeb/ElectroniceDeviceWeb/Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectroniceDeviceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

ElectroniceDeviceWeb/ElectroniceDeviceWeb/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectroniceDeviceWeb.Models;

namespace ElectroniceDeviceWeb.Controllers
{
    public class CustomerController : Controller
    {

        public CustomerController()
        {
        }
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

    }
}

ElectroniceDeviceWeb/ElectroniceDeviceWeb/Views/Customer/Index.cshtml
@model ElectroniceDeviceWeb.Models.Customer

@{
    ViewBag.Title = "Imdex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Index customer
            </div>
            
        </div>
    </div>
</div>

ElectroniceDeviceWeb/ElectroniceDeviceWeb/Views/Customer/Login.cshtml
@model  ElectroniceDeviceWeb.Models.Customer

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Login
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Login", "Customer", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="login" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>