ElectroniceDeviceWeb/ElectroniceDeviceWeb/Controllers/ProductController.cs
using ElectroniceDeviceWeb.Models;
using ElectroniceDeviceWeb.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectroniceDeviceWeb.Controllers
{
    public class ProductController : Controller
    {
        private ElectricDeviceDBEntities DB;

        public ProductController()
        {
            DB = new ElectricDeviceDBEntities();
        }

        // GET: Product
        public ActionResult Index()
        {
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.CategorySelectListItem = (from item in DB.Categories
                                                       select new SelectListItem()
                                                       {
                                                           Text = item.CategoryName,
                                                           Value = item.CategoryId.ToString(),
                                                           Selected = true
                                                       });

            return View(productViewModel);
        }

        [HttpPost]
        public JsonResult Index(ProductViewModel productViewModel)
        {
            string newImage = Guid.NewGuid() + Path.GetExtension(productViewModel.ImagePath.FileName);
            string path = "~/Image/" + newImage;
            productViewModel.ImagePath.SaveAs(Server.MapPath(path));

            Product item = new Product
            {
                ImagePath = path,
                ProductName = productViewModel.ProductName,
                CategoryID = productViewModel.CategoryID,
                Desciption = productViewModel.Description,
                ProductID = Guid.NewGuid(),
                ProductPrice = productViewModel.ProductPrice
            };

            DB.Products.Add(item);
            try { 
            DB.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                Exception raise = e;
                foreach (var validationErrors in e.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting  
                        // the current instance as InnerException  
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }

            return Json(data: new { Success = true, Message = "item is added" }, behavior: JsonRequestBehavior.AllowGet);
        }
    }
}

ElectroniceDeviceWeb/ElectroniceDeviceWeb/Controllers/ShoppingController.cs
using ElectroniceDeviceWeb.Models;
using ElectroniceDeviceWeb.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectroniceDeviceWeb.Controllers
{
    public class ShoppingController : Controller
    {
        private ElectricDeviceDBEntities DB;

        public ShoppingController()
        {
            DB = new ElectricDeviceDBEntities();
        }

        // GET: Shopping
        public ActionResult Index()
        {
            IEnumerable<ShoppingViewModel> shoppingViewModels = (from item in DB.Products
                                                                 join cate in DB.Categories
                                                                 on item.CategoryID equals cate.CategoryId
                                                                 select new ShoppingViewModel()
                                                                 {
                                                                     ImagePath = item.ImagePath,
                                                                     ProductName = item.ProductName,
                                                                     Description = item.Desciption,
                                                                     ProductPrice = item.ProductPrice,
                                                                     ProductID = item.ProductID,
                                                                     Category = cate.CategoryName,
                                                                 });
            return View(shoppingViewModels);
        }
    }
}

ElectroniceDeviceWeb/ElectroniceDeviceWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Điên Tử Việt</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Điên Tử Việt", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Mua Sắm", "Index", "Shopping")</li>
                    <li>@Html.ActionLink("Thêm Sản Phẩm", "Index", "Product")</li>
                    <li>@Html.ActionLink("Về Chúng Tôi", "About", "Home")</li>
                    <li>@Html.ActionLink("Liên Hệ", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - chúng tôi chuyên bán các mặt hàng công nghệ các loại</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>